/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SprintPlanRouteImport } from './routes/sprint-plan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardLiveRouteImport } from './routes/dashboard.live'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardChatbotRouteImport } from './routes/dashboard.chatbot'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'

const SprintPlanRoute = SprintPlanRouteImport.update({
  id: '/sprint-plan',
  path: '/sprint-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/dashboard/performance',
  path: '/dashboard/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/dashboard/live',
  path: '/dashboard/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/dashboard/courses',
  path: '/dashboard/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChatbotRoute = DashboardChatbotRouteImport.update({
  id: '/dashboard/chatbot',
  path: '/dashboard/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/dashboard/attendance',
  path: '/dashboard/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/dashboard/assignments',
  path: '/dashboard/assignments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sprint-plan': typeof SprintPlanRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sprint-plan': typeof SprintPlanRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sprint-plan': typeof SprintPlanRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/sprint-plan'
    | '/dashboard/assignments'
    | '/dashboard/attendance'
    | '/dashboard/chatbot'
    | '/dashboard/courses'
    | '/dashboard/live'
    | '/dashboard/payments'
    | '/dashboard/performance'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/sprint-plan'
    | '/dashboard/assignments'
    | '/dashboard/attendance'
    | '/dashboard/chatbot'
    | '/dashboard/courses'
    | '/dashboard/live'
    | '/dashboard/payments'
    | '/dashboard/performance'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/sprint-plan'
    | '/dashboard/assignments'
    | '/dashboard/attendance'
    | '/dashboard/chatbot'
    | '/dashboard/courses'
    | '/dashboard/live'
    | '/dashboard/payments'
    | '/dashboard/performance'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SprintPlanRoute: typeof SprintPlanRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardChatbotRoute: typeof DashboardChatbotRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sprint-plan': {
      id: '/sprint-plan'
      path: '/sprint-plan'
      fullPath: '/sprint-plan'
      preLoaderRoute: typeof SprintPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/dashboard/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/dashboard/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chatbot': {
      id: '/dashboard/chatbot'
      path: '/dashboard/chatbot'
      fullPath: '/dashboard/chatbot'
      preLoaderRoute: typeof DashboardChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/dashboard/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/dashboard/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SprintPlanRoute: SprintPlanRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardChatbotRoute: DashboardChatbotRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
